version: 2.1

orbs:
  win: circleci/windows@2.2.0

executors:
  ubuntu:
    docker:
      - image: ubuntu:latest

jobs:
  test:
    parameters:
      version:
        type: string
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - run:
          name: "a test of << parameters.version >>"
          command: "echo hey"

workflows:
  workflow:
    jobs:
      - test:
          name: test-v0.1-on-ubuntu
          version: "0.1"
          executor: ubuntu
      - test:
          name: test-v0.1-on-win/default
          version: "0.1"
          executor: win/default
      - test:
          name: test-v0.2-on-ubuntu
          version: "0.2"
          executor: ubuntu
      - test:
          name: test-v0.2-on-win/default
          version: "0.2"
          executor: win/default
