version: 2.1

orbs:
  win: circleci/windows@2.2.0

executors:
  ubuntu:
    docker:
      - image: ubuntu:latest

jobs:
  test:
    parameters:
      version:
        type: string
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - run:
          name: "a test of << parameters.version >>"
          command: "echo hey"
  build:
    parameters:
      version:
        type: string
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - run:
          name: "a build of << parameters.version >>"
          command: "echo hey"
  all-done:
    docker:
      - image: ubuntu:latest
    steps:
      - run: echo all done

workflows:
  workflow:
    jobs:
      - test:
          matrix:
            parameters:
              version: ["0.1", "0.2", "0.3"]
              executor: [ubuntu, win/default]
          name: "test-<< matrix.executor >>-<<matrix.version >>"
      - build:
          matrix:
            parameters:
              version: ["0.1", "0.2", "0.3"]
              executor: [ubuntu, win/default]
          requires:
            - "test-<< matrix.executor >>-<<matrix.version >>"
      - all-done:
          requires:
            - build
