version: 2.1

orbs:
  win: circleci/windows@2.2.0

executors:
  ubuntu:
    docker:
      - image: ubuntu:latest

jobs:
  test:
    parameters:
      version:
        type: string
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - run:
          name: "a test of << parameters.version >>"
          command: "echo hey"
  build:
    parameters:
      version:
        type: string
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - run:
          name: "a build of << parameters.version >>"
          command: "echo hey"


workflows:
  workflow:
    jobs:
      - test:
          matrix:
            parameters:
              version: ["0.1", "0.2"]
              executor: [ubuntu, "win/default"]
          name: test-<< matrix.version >>-on-<< matrix.executor >>
      - build:
          matrix:
            parameters:
              version: ["0.1", "0.2"]
              executor: [ubuntu, "win/default"]
          requires:
            - test-<< matrix.version >>-on-<< matrix.executor >>
