version: 2.1

orbs:
  win: circleci/windows@2.2.0

executors:
  ubuntu:
    docker:
      - image: ubuntu:latest

jobs:
  test:
    parameters:
      version:
        type: string
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - run:
          name: "a test of << parameters.version >>"
          command: "echo hey"
  build:
    parameters:
      version:
        type: string
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - run:
          name: "a build of << parameters.version >>"
          command: "echo hey"
  all-done:
    executor: ubuntu
    steps:
      - run: echo hello world

workflows:
  workflow:
    jobs:
      - test:
          matrix:
            parameters:
              version: ["0.1", "0.2"]
              executor: [ubuntu, win/default]
            exclude:
              - version: "0.2"
                executor: win/default
