version: 2.1
orbs:
  win: circleci/windows@2.2.0

commands:
  test:
    parameters:
      version:
        type: string
    steps:
      - run:
          name: a great success on version << parameters.version >>!
          command: "echo << parameters.version >>"
executors:
  ubuntu:
    docker:
      - image: ubuntu:latest
  fedora:
    docker:
      - image: fedora:latest
  macos:
    docker:
      - image: ubuntu:latest

jobs:
  run-tests:
    parameters:
      version:
        type: string
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - test:
          version: << parameters.version >>
  build:
    parameters:
      version:
        type: string
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - run: "echo building for << parameters.version >>"
  all-done:
    docker:
      - image: ubuntu:latest
    steps:
      - run: echo "yay"

workflows:
  workflow:
    jobs:
      - run-tests:
          matrix:
            parameters:
              version: ["0.1", "0.2"]
              executor: [ubuntu, fedora, win/default]
          name: test-v<< matrix.version >>-on-<< matrix.executor >>
      - build:
          matrix:
            parameters:
              version: ["0.1", "0.2"]
              executor: [ubuntu, fedora, win/default]
          name: build-v<< matrix.version >>-on-<< matrix.executor >>
          requires:
            - test-v<< matrix.version >>-on-<< matrix.executor >>
      - all-done:
          requires:
            - build
